// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wQ4RJSg4PPFwQX7RMUQQuF
// Component: iWxKIIhnXwUN

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: wQ4RJSg4PPFwQX7RMUQQuF/projectcss
import sty from "./PlasmicProjectAudioAvatar.module.css"; // plasmic-import: iWxKIIhnXwUN/css

createPlasmicElementProxy;

export type PlasmicProjectAudioAvatar__VariantMembers = {};
export type PlasmicProjectAudioAvatar__VariantsArgs = {};
type VariantPropType = keyof PlasmicProjectAudioAvatar__VariantsArgs;
export const PlasmicProjectAudioAvatar__VariantProps =
  new Array<VariantPropType>();

export type PlasmicProjectAudioAvatar__ArgsType = {};
type ArgPropType = keyof PlasmicProjectAudioAvatar__ArgsType;
export const PlasmicProjectAudioAvatar__ArgProps = new Array<ArgPropType>();

export type PlasmicProjectAudioAvatar__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultProjectAudioAvatarProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProjectAudioAvatar__RenderFunc(props: {
  variants: PlasmicProjectAudioAvatar__VariantsArgs;
  args: PlasmicProjectAudioAvatar__ArgsType;
  overrides: PlasmicProjectAudioAvatar__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProjectAudioAvatar__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProjectAudioAvatar__VariantsArgs;
    args?: PlasmicProjectAudioAvatar__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicProjectAudioAvatar__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicProjectAudioAvatar__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProjectAudioAvatar__ArgProps,
          internalVariantPropNames: PlasmicProjectAudioAvatar__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProjectAudioAvatar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProjectAudioAvatar";
  } else {
    func.displayName = `PlasmicProjectAudioAvatar.${nodeName}`;
  }
  return func;
}

export const PlasmicProjectAudioAvatar = Object.assign(
  // Top-level PlasmicProjectAudioAvatar renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicProjectAudioAvatar
    internalVariantProps: PlasmicProjectAudioAvatar__VariantProps,
    internalArgProps: PlasmicProjectAudioAvatar__ArgProps
  }
);

export default PlasmicProjectAudioAvatar;
/* prettier-ignore-end */
